settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: setzna
  path: .
  commands:
    install:
      status: true
      method: go build -o setzna_bin ./cmd/setzna/main.go
    run:
      status: true
      method: ./setzna_bin
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
