version: '3'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        container_name: setzna_app
        volumes:
            - .:/go/src/setzna
        command: go run main.go
    mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: golang
            MYSQL_USER: golang 
            MYSQL_PASSWORD: golang
            MYSQL_DATABASE: golang
        container_name: setzna_mysql