version: '3'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        container_name: setzna_app
        volumes:
            - .:/go/src/setzna
        command: go run cmd/setzna/main.go
        environment: 
            DB_USER: setzna
            DB_PASS: setzna
            DB_HOST: mysql
            DB_NAME: setzna
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: setzna 
            MYSQL_PASSWORD: setzna
            MYSQL_DATABASE: setzna
        container_name: setzna_mysql
        volumes:
            - ./mysql_data:/var/lib/mysql